KaysCrochet/urls.py
from django.contrib import admin
from django.urls import include, path
import logging
from django.http import HttpResponseServerError

# Create a logger for this module
logger = logging.getLogger(__name__)

urlpatterns = [
    path("", include("kayscrochetapp.urls")),
    path("admin/", admin.site.urls),
    path("", include("pwa.urls")),
]


def handler500(request, *args, **argv):
    # Log an error if a 500 error occurs
    logger.error("An error occurred: Internal Server Error")

    # You can customize the log message and log level based on your needs.

    # Return an error response or handle it as needed
    return HttpResponseServerError("An error occurred. Please try again later.")

kayscrochetapp/urls.py
from django.urls import path
from . import views
from .views import add_to_cart, cart, remove_from_cart, like_item, SuccessView, CancelView

app_name = 'kayscrochetapp'
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:item_id>/like/", views.like, name="like"),
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('signout/', views.signout, name='signout'),
    path('cart/', cart, name='cart'),
    path('<int:pk>/item/', add_to_cart, name='add_to_cart'),
    path('<int:item_id>/cart/remove/', remove_from_cart, name='remove_from_cart'),
    path('like_item/', like_item, name='like_item'),
    path('cancel/', CancelView.as_view(), name='cancel'),
    path('success/', SuccessView.as_view(), name='success'),
    path('create_payment_intent/', views.create_payment_intent, name='create_payment_intent'),
    path('clear_cart/', views.clear_cart, name='clear_cart'),
]

kayscrochetapp/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import AbstractUser
from django.utils import timezone


# table to add item and its details
class Item(models.Model):
    item_title = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to='items_images/', blank=True, null=True)
    image2 = models.ImageField(upload_to='items_images/', blank=True, null=True)
    image3 = models.ImageField(upload_to='items_images/', blank=True, null=True)
    image4 = models.ImageField(upload_to='items_images/', blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    pub_date = models.DateTimeField("date published")
    no_of_likes = models.IntegerField(default=0)
    is_sold = models.BooleanField(default=False)
    total_quantity = models.IntegerField(default=1)
    is_preorder = models.BooleanField(default=False)
    preorder_time = models.CharField(max_length=50, default="", blank=True)

    def decrease_stock(self, quantity):
        self.total_quantity = max(0, self.total_quantity - quantity)
        if self.total_quantity == 0:
            self.is_sold = True
        self.save()

    def __str__(self):
        return self.item_title

    def save(self, *args, **kwargs):
        if not self.preorder_time:
            self.preorder_time = ""
        super().save(*args, **kwargs)

    # order by published recently
    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        now = timezone.now()
        one_day_ago = now - timezone.timedelta(days=1)

        # Make it timezone-aware
        if timezone.is_naive(self.pub_date):
            self.pub_date = timezone.make_aware(self.pub_date)

        return one_day_ago <= self.pub_date <= now


# table to add choices to vote on of future crocheted items
class Choice(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    likes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


# table to store likes
class LikeItem(models.Model):
    item_id = models.CharField(max_length=500)
    username = models.CharField(max_length=100)

    def __str__(self):
        return self.username


# table to store customer order info
class Customerorder(models.Model):
    full_name = models.CharField(max_length=100)
    street = models.CharField(max_length=255)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=20)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    item_title = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.full_name}'s Order"

    class Meta:
        verbose_name = "Customer_Order"
        verbose_name_plural = "Customer_Orders"

kayscrochetapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class SignInForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class AddToCartForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, initial=1, widget=forms.NumberInput(attrs={'class': 'form-control'}))

kayscrochetapp/views.py
from decimal import Decimal

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import send_mail
from django.db import transaction
from django.http import HttpResponseRedirect, JsonResponse, HttpResponseServerError
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST
from django.views import generic
from django.views.generic import TemplateView

from .forms import SignUpForm, SignInForm, AddToCartForm
from .models import Choice, Item, LikeItem, Customerorder
import stripe
import logging

# Define the logger
logger = logging.getLogger(__name__)


class IndexView(generic.ListView):
    template_name = "kayscrochetapp/index.html"
    context_object_name = "latest_item_list"

    def dispatch(self, request, *args, **kwargs):
        # Log that the IndexView is being accessed
        logger.info("IndexView accessed.")
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        try:
            queryset = Item.objects.order_by("-pub_date")[:100]
            # Example log statement
            logger.info("IndexView queryset retrieved successfully.")
            return queryset
        except Exception as e:
            # Log the exception details
            logger.error(f"Error retrieving queryset in IndexView: {e}")
            # You might want to raise or handle the exception accordingly
            raise

class DetailView(generic.DetailView):
    model = Item
    template_name = "kayscrochetapp/detail.html"

    @method_decorator(login_required(login_url='kayscrochetapp:signin'))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class ResultsView(generic.DetailView):
    model = Item
    template_name = "kayscrochetapp/results.html"

    @method_decorator(login_required(login_url='kayscrochetapp:signin'))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


def like(request, item_id):
    item = get_object_or_404(Item, pk=item_id)
    try:
        selected_choice = item.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "kayscrochetapp/detail.html",
            {
                "item": item,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.likes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("kayscrochetapp:results", args=(item.id,)))


def signup(request):
    try:
        if request.method == 'POST':
            form = SignUpForm(request.POST)
            if form.is_valid():
                user = form.save()
                login(request, user)
                return redirect(reverse('kayscrochetapp:index'))
        else:
            form = SignUpForm()

        return render(request, 'kayscrochetapp/signup.html', {'form': form})
    except Exception as e:
        # Log an error if an exception occurs
        logger.error("An error occurred in the signup view: %s", str(e))

        # Return an error response or handle it as needed
        return HttpResponseServerError("An error occurred during signup.")


def signin(request):
    if request.method == 'POST':
        form = SignInForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return redirect(reverse('kayscrochetapp:index'))
            else:
                messages.error(request, 'Wrong username or password entered.')
    else:
        form = SignInForm()
    return render(request, 'kayscrochetapp/signin.html', {'form': form})


def signout(request):
    logout(request)
    return redirect(reverse('kayscrochetapp:index'))


def add_to_cart(request, pk):
    try:
        item = get_object_or_404(Item, pk=pk)
        quantity = int(request.POST.get('quantity', 1))

        # Skip stock check if the item is available for preorder
        if not (item.is_sold and item.is_preorder):
            if item.total_quantity < quantity:
                messages.error(request, f'Not enough stock available.')
                return redirect('kayscrochetapp:detail', pk=pk)

        cart = request.session.get('kayscrochetapp:cart', {})
        item_key = str(item.pk)

        if item_key in cart:
            cart[item_key]['quantity'] = quantity
        else:
            cart[item_key] = {'quantity': quantity, 'price': str(item.price), 'total_price': str(Decimal(item.price) * Decimal(quantity))}

        request.session['kayscrochetapp:cart'] = cart
        messages.success(request, "Item added to cart.")
        return redirect('kayscrochetapp:cart')
    except ObjectDoesNotExist:
        messages.error(request, 'Item not found.')
        return redirect('kayscrochetapp:index')
    except ValueError:
        messages.error(request, 'Invalid quantity.')
        return redirect('kayscrochetapp:detail', pk=pk)
    except Exception as e:
        print(f"Error adding item to cart: {e}")
        messages.error(request, 'An error occurred while processing your request.')
        return redirect('kayscrochetapp:cart')


@login_required(login_url='kayscrochetapp:signin')
def cart(request):
    # Retrieve the cart data from the session
    cart = request.session.get('kayscrochetapp:cart', {})
    items = []

    for item_id, item_data in cart.items():
        item = get_object_or_404(Item, pk=item_id)
        quantity = item_data['quantity']
        price_str = item_data['price']
        # Convert price back to Decimal
        price = Decimal(price_str)
        total_price = quantity * price  # Calculate total price for the item

        items.append({'item': item, 'quantity': quantity, 'price': price, 'total_price': total_price})

    context = {'items': items, 'STRIPE_PUBLIC_KEY': settings.STRIPE_PUBLIC_KEY}
    return render(request, 'kayscrochetapp/cart.html', context)


@require_POST
def remove_from_cart(request, item_id):
    # Retrieve the cart data from the session
    cart = request.session.get('kayscrochetapp:cart', {})

    # Check if the item is in the cart
    if str(item_id) in cart:
        # Get the removed item's total price
        removed_item_total_price = float(cart[str(item_id)]['total_price'])

        # Remove the item from the cart
        del cart[str(item_id)]

        # Save the updated cart back to the session
        request.session['kayscrochetapp:cart'] = cart

        # Print debug information
        print(f"Item {item_id} removed from the cart")

        return JsonResponse({'removed_item_total_price': removed_item_total_price})
    else:
        # If the item is not in the cart, return an error response
        return JsonResponse({'error': f'Item {item_id} not found in the cart'}, status=400)


def like_item(request):
    username = request.user.username
    item_id = request.GET.get('item_id')

    item = get_object_or_404(Item, id=item_id)

    like_filter = LikeItem.objects.filter(item_id=item_id, username=username).first()

    if like_filter is None:
        new_like = LikeItem.objects.create(item_id=item_id, username=username)
        new_like.save()
        item.no_of_likes = item.no_of_likes + 1
    else:
        like_filter.delete()
        item.no_of_likes = item.no_of_likes - 1

    item.save()

    # Return JSON response with updated like count as an integer
    return JsonResponse({'no_of_likes': item.no_of_likes})


class SuccessView(TemplateView):
    template_name = "kayscrochetapp/payment_success.html"


class CancelView(TemplateView):
    template_name = "kayscrochetapp/payment_canceled.html"


stripe.api_key = settings.STRIPE_SECRET_KEY

# Define a list of allowed IP addresses or domains
ALLOWED_ADDRESSES = [ 'https://www.kayscrochet.us', 'www.kayscrochet.us', 'kayscrochet.us', 'https://kayscrochetapp-e13180bf49a3.herokuapp.com/']


@require_POST
def create_payment_intent(request):
    try:
        # Verify that the request is coming from an allowed IP address or domain
        client_address = request.META.get('REMOTE_ADDR')
        client_host = request.META.get('HTTP_HOST')
        if client_address not in ALLOWED_ADDRESSES and client_host not in ALLOWED_ADDRESSES:
            raise PermissionError("Unauthorized access")

        # Extract the amount from the request
        amount_cents = int(request.POST.get('amount', 0))

        # Validate required fields
        if not amount_cents:
            raise ValueError("Amount is required")

        # Convert amount to dollars
        amount_dollars = Decimal(amount_cents) / Decimal(100.0)

        # Create a PaymentIntent
        intent = stripe.PaymentIntent.create(
            amount=amount_cents,
            currency='usd',
            payment_method_types=['card'],
        )

        return JsonResponse({'clientSecret': intent.client_secret})

    except PermissionError as pe:
        logger.error(f"PermissionError: {pe}")
        return JsonResponse({'error': 'Permission denied'}, status=403)

    except stripe.error.CardError as ce:
        logger.error(f"CardError: {ce.error.message}")
        return JsonResponse({'error': f'Card error: {ce.error.message}'}, status=400)

kayscrochetapp/templates/kayscrochetapp/detail.html
{% extends 'base_generic.html' %}
{% load custom_filters %}

{% block title %}{{ item.item_title }} Details{% endblock %}

{% if user.is_authenticated %}
{% block content %}
{% if not item.is_sold and not item.is_preorder %}
    <form method="post" action="{% url 'kayscrochetapp:add_to_cart' pk=item.pk %}">
        {% csrf_token %}
        <div style="display: flex; align-items: center; padding-left: 1rem">
            <label for="quantity">Quantity:</label>
            <input type="number" id="quantity" name="quantity" min="1" max="{{ item.total_quantity }}" value="1">
            
            <button onmouseover="this.style.boxShadow='0 0 10px rgba(0, 0, 0, 0.5)'" onmouseout="this.style.boxShadow='none'" type="submit"
                    title="Add To Cart" style="color: hsl(270, 50%, 60%);">
                <i class="fas fa-cart-plus fa-lg"></i>
            </button>
        </div>
    </form>
{% elif item.is_sold and item.is_preorder %}
<form method="post" action="{% url 'kayscrochetapp:add_to_cart' pk=item.pk %}">
    {% csrf_token %}
    <div style="display: flex; align-items: center; padding-left: 1rem">
        <label for="quantity">Quantity:</label>
        <input type="number" id="quantity" name="quantity" min="1" value="1"> 
        <button type="submit" style="color: hsl(270, 50%, 60%);" 
                onmouseover="this.style.boxShadow='0 0 10px rgba(0, 0, 0, 0.5)'" 
                onmouseout="this.style.boxShadow='none'">PREORDER</button>
    </div>
</form>
{% elif not item.is_sold and item.is_preorder %}
    <form method="post" action="{% url 'kayscrochetapp:add_to_cart' pk=item.pk %}">
        {% csrf_token %}
        <div style="display: flex; align-items: center; padding-left: 1rem">
            <label for="quantity">Quantity:</label>
            <input type="number" id="quantity" name="quantity" min="1" max="{{ item.total_quantity }}" value="1">
            
            <button onmouseover="this.style.boxShadow='0 0 10px rgba(0, 0, 0, 0.5)'" onmouseout="this.style.boxShadow='none'" type="submit"
                    title="Add To Cart" style="color: hsl(270, 50%, 60%);">
                <i class="fas fa-cart-plus fa-lg"></i>
            </button>
        </div>
    </form>
{% endif %}

<form action="{% url 'kayscrochetapp:like' item.id %}" method="post">
{% csrf_token %}
    <fieldset style="color: hsl(270, 50%, 60%); border: 0.0625rem solid hsl(270, 50%, 60%);">
        <legend style="margin-bottom: 0"><h3 style="text-transform: uppercase;   color: hsl(270, 50%, 60%);
              text-shadow: 2px 2px 6px rgba(100, 100, 150, 0.9); /* Darkened shadow color and closer position */
              background: linear-gradient(90deg, hsl(270, 50%, 60%), hsl(270, 50%, 80%));
              -webkit-background-clip: text;
              background-clip: text;">{{ item.item_title }}</h3></legend>
        {% if item.total_quantity > 0 %}
            <div><p>  {{ item.total_quantity }} still available</p></div>
        {% else %}
            <div><p>Out of Stock</p></div>
        {% endif %}
        <div style="padding: .5rem;" >
            {% if item.image %}
                <img src="{{ item.image.url }}" alt="{{ item.item_title|safe }}" title="{{ item.item_title }}"
                     style="max-height: 60vh; width: 40%; height: auto; border: 0.1rem solid hsl(270, 50%, 60%); border-radius: 0.3125rem; margin-top: -.75rem">
            {% endif %}
            {% if item.image2 %}
                <img src="{{ item.image2.url }}" alt="{{ item.item_title|safe }}" title="{{ item.item_title }}"
                     style="max-height: 60vh; width: 40%; height: auto; border: 0.1rem solid hsl(270, 50%, 60%); border-radius: 0.3125rem; margin-top: -.75rem">
            {% endif %}
        </div>
        <div style="padding: .5rem">
            {% if item.image3 %}
                <img src="{{ item.image3.url }}" alt="{{ item.item_title|safe }}" title="{{ item.item_title }}"
                     style="max-height: 60vh; width: 40%; height: auto; border: 0.1rem solid hsl(270, 50%, 60%); border-radius: 0.3125rem; margin-top: -.75rem">
            {% endif %}
            {% if item.image4 %}
                <img src="{{ item.image4.url }}" alt="{{ item.item_title|safe }}" title="{{ item.item_title }}"
                     style="max-height: 60vh; width: 40%; height: auto; border: 0.1rem solid hsl(270, 50%, 60%); border-radius: 0.3125rem; margin-top: -.75rem">
            {% endif %}
        </div>
        <h4 style="margin-top: -.75rem">Description:</h4>
        <p style="margin-top: -.5rem">{{ item.description }}</p>
        <!-- Check if item is sold -->
        {% if item.is_sold and not item.is_preorder%}
            <p></p>
        {% else %}
            <h4 style="margin-top: -.75rem">Price:</h4>
            <p style="margin-top: -.5rem">${{ item.price }}</p>  
        {% endif %} 
        <h4 style="margin-top: -.75rem">Published On:</h4>
        <p style="margin-top: -.5rem">{{ item.pub_date|date:"M j, Y" }}</p>
        <div class="d-flex justify-content-left align-items-center" style="margin-top: -1rem">
            <div>
                {% if user.is_authenticated %}
                    <a href="javascript:void(0);" class="like-icon text-dark" data-item-id="{{ item.id }}">
                        <i class="fa fa-heart fa-2x" style="color: red;" title="Click to like"></i>
                    </a>
                {% else %}
                    <span class="like-icon" data-bs-toggle="modal" data-bs-target="#loginModal" >
                        <i class="fa fa-heart fa-2x" style="color: red; cursor: pointer;" title="Must be logged in to like"></i>
                    </span>
                {% endif %}
            </div>
            <div>
                {% if item.no_of_likes == 0 %}
                    <p id="like-count-{{ item.id }}"> 's 0</p>
                {% elif item.no_of_likes == 1 %}
                    <p id="like-count-{{ item.id }}"> 's {{item.no_of_likes}}</p>
                {% else %}
                    <p id="like-count-{{ item.id }}"> 's {{item.no_of_likes}}</p>
                {% endif %}
            </div>
        </div>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% if item.choice_set.count > 0 %}
            <h4 style="color: hsl(270, 50%, 60%);">Vote on Styles For Kay's Crochet To Make:</h4>
            {% for choice in item.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
        {% endif %}
        {% if item.choice_set.count > 0 %}
            <input type="submit" value="VOTE FOR STYLES" onmouseover="this.style.boxShadow='0 0 10px rgba(0, 0, 0, 0.5)'"
                   onmouseout="this.style.boxShadow='none'" style="color: hsl(270, 50%, 60%); display: flex; justify-content: center; align-items: center; vertical-align: middle; ">
            <button type="button" onmouseover="this.style.boxShadow='0 0 10px rgba(0, 0, 0, 0.5)'"
                    onmouseout="this.style.boxShadow='none'" class="button"
                    onclick="window.location.href = '{% url 'kayscrochetapp:results' item.id%}'"
                    style="color: hsl(270, 50%, 60%);">SEE STYLE VOTES</button>
        {% endif %}
    </fieldset>
</form>
    
<script>
// Add click event listener to the like icon in index.html
document.addEventListener('DOMContentLoaded', function () {
    var likeIcons = document.querySelectorAll('.like-icon');
    likeIcons.forEach(function (likeIcon) {
        likeIcon.addEventListener('click', function () {
            // Get the item ID from the data attribute
            var itemId = likeIcon.dataset.itemId;

            // Make an AJAX request to the like_item view
            $.ajax({
                type: 'GET',
                url: '/like_item/?random=' + Math.random(),  // Adding random parameter to prevent caching
                data: {
                    'item_id': itemId,
                },
                success: function (data) {
                    // Update the like count and 's on the client side
                    var likeCountElement = document.querySelector('#like-count-' + itemId);

                    // Check if likeCountElement exists
                    if (likeCountElement) {
                        likeCountElement.innerHTML = ' <p id="like-count-' + itemId + '"> \'s ' + data.no_of_likes + '</p>';

                        // Log to verify the updated value
                        console.log('Updated like count:', data.no_of_likes);

                        // Force a DOM update
                        likeCountElement.innerHTML = likeCountElement.innerHTML;
                    } else {
                        console.log('likeCountElement not found.');
                    }
                },
                error: function (error) {
                    console.log('Error:', error);
                }
            });
        });
    });
});
</script>
<script>
document.addEventListener('DOMContentLoaded', function () {
    var isPreorderAvailable = {% if item.is_sold and item.is_preorder %}true{% else %}false{% endif %};
    var quantityInput = document.getElementById('quantity');

    if (quantityInput) {
        quantityInput.addEventListener('change', function() {
            if (!isPreorderAvailable) {
                var maxQuantity = {{ item.total_quantity }};
                if (this.value > maxQuantity) {
                    this.value = maxQuantity;
                }
            }
        });
    }
});

</script>


{% endblock %}
{% endif %}

kayscrochetapp/templates/kayscrochetapp/payment_canceled.html
{% extends 'base_generic.html' %}

{% block title %}Payment Canceled{% endblock %}

{% block content %}
    <fieldset style="color: hsl(270, 50%, 60%); border: 0.0625rem solid hsl(270, 50%, 60%);">
        <form>
            <h1 style="  color: hsl(270, 50%, 60%);
                  text-shadow: 2px 2px 6px rgba(100, 100, 150, 0.9); /* Darkened shadow color and closer position */
                  background: linear-gradient(90deg, hsl(270, 50%, 60%), hsl(270, 50%, 80%));
                  -webkit-background-clip: text;
                  background-clip: text;">Payment Canceled</h1>
            <p>Please click Home or contact us at our Instagram, TikTok, or Help above.</p>
        </form>
    </fieldset>
{% endblock %}

kayscrochetapp/templates/kayscrochetapp/payment_success.html
{% extends 'base_generic.html' %}

{% block title %}Payment Success{% endblock %}

{% block content %}
    <fieldset style="color: hsl(270, 50%, 60%); border: 0.0625rem solid hsl(270, 50%, 60%);">
        <form>
        <h1 style="  color: hsl(270, 50%, 60%);
                text-shadow: 2px 2px 6px rgba(100, 100, 150, 0.9); /* Darkened shadow color and closer position */
                background: linear-gradient(90deg, hsl(270, 50%, 60%), hsl(270, 50%, 80%));
                -webkit-background-clip: text;
                background-clip: text;">Payment Successful!</h1>
            <p>Thank you for your purchase. An invoice has been sent to your email inbox or email spam.</p>
            <p>Please click Home or contact Kay's Crochet at kayscrochetus@gmail.com or by clicking the Instagram and TikTok icons below.</p>
        </form>
    </fieldset>
{% endblock %}

kayscrochetapp/templates/kayscrochetapp/signin.html
{% extends 'base_generic.html' %}

{% block title %}LOGIN - Kay's Crochet{% endblock %}

{% block content %}
    <div class="flex-grow-1" style="color: hsl(270, 50%, 60%);">
        <form method="post">
            {% csrf_token %}
            <fieldset style="border: 0.0625rem solid hsl(270, 50%, 60%);">
                <legend style="  color: hsl(270, 50%, 60%);
                  text-shadow: 2px 2px 6px rgba(100, 100, 150, 0.9); /* Darkened shadow color and closer position */
                  background: linear-gradient(90deg, hsl(270, 50%, 60%), hsl(270, 50%, 80%));
                  -webkit-background-clip: text;
                  background-clip: text;">LOG IN TO KAY'S CROCHET:</legend>
                <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
                {{ form.as_p }}
                <button onmouseover="this.style.boxShadow='0 0 10px rgba(0, 0, 0, 0.5)'" onmouseout="this.style.boxShadow='none'" 
                        type="submit" style="color: hsl(270, 50%, 60%); font-weight: normal;">LOGIN</button>
                <p>Click REGISTER to create an account:</p>
                <div>
                    <button type="button" class="button" onmouseover="this.style.boxShadow='0 0 10px rgba(0, 0, 0, 0.5)'"
                            onmouseout="this.style.boxShadow='none'" onclick="window.location.href = '{% url 'kayscrochetapp:signup' %}'" style="color: hsl(270, 50%, 60%);">REGISTER</button>
                </div>
            </fieldset>
        </form>
    </div>
    <div>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    </div>
    
    <script>
        // Automatically close error messages after 5 seconds (adjust as needed)
        setTimeout(function() {
            document.querySelector('.messages').style.display = 'none';
        }, 3000);
    </script>
{% endblock %}

kayscrochetapp/templates/kayscrochetapp/signout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Log Out</title>
</head>
<body>
<form method="post" action="{% url 'kayscrochetapp:signout' %}">
    {% csrf_token %}
    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
    <button onmouseover="this.style.boxShadow='0 0 10px rgba(0, 0, 0, 0.5)'" onmouseout="this.style.boxShadow='none'"
            type="submit" style="color: hsl(270, 50%, 60%); font-weight: normal;">LOGOUT</button>
</form>
</body>
</html>